spring.application.name=marble-store-backend
spring.datasource.username=root
spring.datasource.password=abhishek@007
spring.datasource.url=jdbc:mysql://localhost:3306/marble_store
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#spring.main.allow-circular-references=true

spring.mail.host=${SMTP_HOST:smtp.gmail.com}
spring.mail.username=${SMTP_USERNAME:}
spring.mail.password=${SMTP_PASSWORD:}
spring.mail.port=${SMTP_PORT:587}
spring.mail.properties.mail.smtp.auth=${SMTP_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${SMTP_STARTTLS:true}

app.frontend-url=${FRONTEND_URL:http://localhost:5173}

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

rupee.sign=${RUPEE_SIGN:&#8377;}

